0model:
  depth: 8
  conv_kernel_size: 11
  weight_shared_blocks: 1
  batch_size: 1
  feed_forward_intermediate_factor: 0.125
  features: 8192
optimizer:
  gradient_accumulation_steps: 1
  one_cycle:
    cycle_first_step_size: 8192
    cycle_second_step_size: 4096
    cycle_min_lr: 0.00015
    cycle_max_lr: 0.0005
    cycle_min_mom: 0.85
    cycle_max_mom: 0.99
log:
  print_interval: 64
